### ISSUE TITLE
Filtering work item by assignee as unassigned does not work

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2253] opened 2017-10-10 06:13 UTC
![screencast from 10-10-2017 11-31-46 am](https://user-images.githubusercontent.com/12949454/31371673-d2d1755e-adaf-11e7-95ab-110dd66c536a.gif)

**Comment by rgarg1** [comment] 2017-10-11 10:47
Duplicate of https://openshift.io/openshiftio/openshiftio/plan/detail/1530

**Closed by rgarg1** 2017-10-11 10:47 UTC
